FROM registry.access.redhat.com/ubi9/go-toolset:9.6 AS builder

COPY ./src .

RUN go mod init k1 && \
    go mod tidy && \
    go build .

FROM registry.access.redhat.com/ubi9/ubi9-micro

COPY --from=builder /opt/app-root/src/k1 .

CMD ./k1
